spring.application.name=murmur

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/murmur}
spring.datasource.username=${POSTGRES_USERNAME:murmur_backend}
spring.datasource.password=${POSTGRES_PASSWORD:backend123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000